Add ability to replay match from specified event
trarbr/csgo_stats pull request #37
Opened 2020-10-20 19:10 UTC by trarbr

2020-10-22 19:20 UTC, nicoeg reviewed
This is so cool! 🤩 

Seems like the total event count is going up as the events are being played. Would it be possible for it to load them all at the beginning?
![image](https://user-images.githubusercontent.com/947230/96919444-0e31b080-14ac-11eb-923c-185137d5f990.png)

Also could you add a comment to the readm explaining how to start it and link to one of the log files as examples?

2020-10-22 19:20 UTC, nicoeg commented
It could also be nice to be able to pause it but let's save that for later

2020-10-22 19:51 UTC, nicoeg requested changes
I've pushed a commit that fixes the white background fade issue. Hope it's okay 😛

2020-10-22 19:51 UTC, nicoeg commented on assets/css/app.scss
>      padding: 20px;
```suggestion
    padding: 20px;
    margin-top: 20px;
```

2020-10-23 19:36 UTC, trarbr commented
> This is so cool! 🤩
> 
> Seems like the total event count is going up as the events are being played. Would it be possible for it to load them all at the beginning?
> 
> Also could you add a comment to the readm explaining how to start it and link to one of the log files as examples?

Great idea :+1: I have added `CsgoStats.load/1` to load all events at once, and then it lets you jump between events as you like to. I have also added a description of load and playback functions to the readme.

2020-10-24 17:32 UTC, nicoeg approved these changes
Cool stuff!

Just an idea: Logfile name could be set as `x-server-instance-token` so that multiple logfiles could be opened at the same time

2020-10-24 19:02 UTC, merged